data = [
    {'name': '9GAG', 'follower_count': 52, 'description': 'Social media platform', 'country': 'China'},
    {'name': 'Ariana Grande', 'follower_count': 183, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 145, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 61, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Camila Cabello', 'follower_count': 49, 'description': 'Musician', 'country': 'Cuba'},
    {'name': 'Cardi B', 'follower_count': 67, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Chris Brown', 'follower_count': 64, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 602, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'David Beckham', 'follower_count': 82, 'description': 'Footballer', 'country': 'United Kingdom'},
    {'name': 'Demi Lovato', 'follower_count': 146, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Drake', 'follower_count': 65, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Dwayne Johnson', 'follower_count': 342, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 87, 'description': 'Comedian', 'country': 'United States'},
    {'name': 'Emma Watson', 'follower_count': 56, 'description': 'Actress', 'country': 'United Kingdom'},
    {'name': 'FC Barcelona', 'follower_count': 85, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Gigi Hadid', 'follower_count': 54, 'description': 'Model', 'country': 'United States'},
    {'name': 'Instagram', 'follower_count': 651, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 230, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 455, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Justin Timberlake', 'follower_count': 59, 'description': 'Musician and actor', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 338, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 127, 'description': 'Reality TV personality and model', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 162, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Khaby Lame', 'follower_count': 79, 'description': 'Comedian', 'country': 'Senegal'},
    {'name': 'Khloé Kardashian', 'follower_count': 108, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 167, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 90, 'description': 'Reality TV personality', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 333, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Lady Gaga', 'follower_count': 271, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 63, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 477, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Maluma', 'follower_count': 50, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Miley Cyrus', 'follower_count': 192, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'NASA', 'follower_count': 56, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 135, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'NBA', 'follower_count': 47, 'description': 'Club basketball competition', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 138, 'description': 'Footballer', 'country': 'Brazil'}
]
